### ISSUE TITLE
Doesn't work with wireshark 3.4.4 on Debian 11

### ISSUE THREAD

**Issue by richardklingler** [andrebdo/wireshark-cc2531#3]
Compiling and installing cc2531 was fine and I can launch the program directly and it responds...

Starting wireshark 3.4.4 shows then the cc2531 capture interface, but no option to enter a channel number....
![wireshark_cc2531](https://user-images.githubusercontent.com/11256235/135971110-c0716fbc-4b0a-484a-b9ab-effeb973bf39.png)

Clicking on cc2531 starts the capture but for obvious reason it can't capture anything:

![wireshark_no_capture](https://user-images.githubusercontent.com/11256235/135971167-7af7c3f6-d320-48b8-9045-e8888aa5a988.png)

**Comment by richardklingler** [comment]
My fault..haven't used wireshark in a while (o;

**Comment by oyvindbrown** [comment]
@richardklingler How did you fix this issue? I get the same issue on my Kali Linux.

**Comment by cyberxml** [comment]
Same problem on Ubuntu 22.04.2 LTS with Wireshark 3.6.2

Had two Digi Zigbee S1talking on a 500ms loop. Same 'no data' error

Experimented with modifying the /usr/lib/x86_64-linux-gnu/wireshark/extcap/cc2531 file with root:wireshark perms but still 'no data'

#-----------------------------------------------------------------

Seems fixed by adding appropriate udev rules

vi /etc/udev/rules.d/54-cc2531.rules
ATTR{idVendor}=="0451", ATTR{idProduct}=="16ae",MODE="660", GROUP="dialout"
udevadm control --reload

make sure your user is in dialout group
unplug and replug CC2531 - should get solid green light on device
